accelerate launch model_train_2.py\
    --model_name_or_path "EleutherAI/polyglot-ko-5.8b" \
    --dataset_path "{데이터 경로}" \
    --num_train_epochs 1 \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --gradient_accumulation_steps 1\
    --learning_rate 1e-4 \
    --optim "paged_adamw_8bit"\
    --r 8 \
    --lora_dropout 0.05 \
    --lora_alpha 32 \
    --adam_beta1 0.9 \
    --adam_beta2 0.99 \
    --bf16 true \
    --output_dir "{모델 저장 경로}" \